skill-0:
  source: /Volumes/Asylum/archimedes/runs/evo-integrity-2026-07-24-repair/tmp/pytest/test_list_multiple_skills0/skill-0
skill-1:
  source: /Volumes/Asylum/archimedes/runs/evo-integrity-2026-07-24-repair/tmp/pytest/test_list_multiple_skills0/skill-1
skill-2:
  source: /Volumes/Asylum/archimedes/runs/evo-integrity-2026-07-24-repair/tmp/pytest/test_list_multiple_skills0/skill-2
